### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yu-dai-alt** [yu-dai-alt/furima_28759#17]
# URL
https://furima-28759.herokuapp.com/

# Basic認証のIDとパスワード
-ID
admin
-パスワード
2222

# 出品者情報
-メールアドレス
d@d.com
-パスワード
test123

# 購入者情報
-メールアドレス
e@e.com
-パスワード
sample123

# クレジットカード情報
-購入用カードの番号
4242424242424242
-期限
12/24
-セキュリティコード
123

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**・商品を削除後、商品の出品ができない**
一度、商品は出品できたのですが商品を削除後に再度、出品をしようとすると出品ができなくなりました。
商品を出品できるように修正しましょう。



※商品購入機能はまだ、確認できていないため上記内容、修正後確認します。
修正し次第、以下の完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by yu-dai-alt** [comment]
ご確認いただき、ありがとうございます。
修正させていただきましたので、再度ご確認のほどよろしくお願いいたします。

#why
商品削除後、商品の出品ができるように設定
# what
-itemマイグレーションファイルimageカラムのnull false設定を変更

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○商品の出品ができない**
ユーザー登録後に商品の出品ができないため、修正をお願いします！

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yu-dai-alt** [comment]
再度ご確認いただきありがとうございます。
申し訳ございません。修正内容がマージされていなかったようです。
再度ご確認ほど、よろしくお願いします。

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、前回からの修正が確認できませんでした。
デプロイを含め再度、本番環境で実装できているか確認をお願いします！

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yu-dai-alt** [comment]
再度ご確認いただきありがとうございます。
申し訳ございません。修正いたしました。
よろしくおねがいします。

**Comment by keisukekodama** [comment]
修正ありがとうございます！
前回の指摘箇所の修正確認できました！
再度、確認させて頂いたところ、新たに以下の不備が見受けられましたので修正をお願いします！

**・商品の購入画面に遷移できない**
「購入画面に進む」ボタンを押すとエラー画面になります。
商品購入画面に遷移できるように修正しましょう。

※商品購入機能はまだ、確認できていないため上記内容、修正後確認します。
修正し次第、以下の完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by yu-dai-alt** [comment]
何度も申し訳ございません。
修正させていただきました。
よろしくお願いいたします。

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
